name: Release

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - id: check-tag
        run: |
          VERSION=${{ steps.get-version.outputs.version }}
          if git fetch --tags && git tag | grep -q "^v$VERSION$"; then
            echo "Tag v$VERSION already exists."
            echo "should_release=false" >> $GITHUB_OUTPUT
          else
            echo "should_release=true" >> $GITHUB_OUTPUT
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi
    outputs:
      should_release: ${{ steps.check-tag.outputs.should_release }}
      version: ${{ steps.get-version.outputs.version }}

  test:
    runs-on: ubuntu-latest
    needs: check-version
    if: needs.check-version.outputs.should_release == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test

  release:
    runs-on: ubuntu-latest
    needs:
      - check-version
      - test
    permissions:
      contents: write
    if: needs.test.result == 'success' && needs.check-version.outputs.should_release == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm build
      - name: Get previous tag
        id: prev-tag
        run: |
          CURRENT_TAG="v${{ needs.check-version.outputs.version }}"
          ALL_TAGS=$(git tag -l "v*" | sort -V)
          PREV_TAG=$(echo "$ALL_TAGS" | grep -B1 "^${CURRENT_TAG}$" | head -n 1)
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag_name: v${{ needs.check-version.outputs.version }}
          name: Release v${{ needs.check-version.outputs.version }}
          draft: true
          body: |
            Full Changelog: [${{ steps.prev-tag.outputs.prev_tag }}...v${{ needs.check-version.outputs.version }}](https://github.com/${{ github.repository }}/compare/${{ steps.prev-tag.outputs.prev_tag }}...v${{ needs.check-version.outputs.version }})
